DROP TABLE MIEMBROS_CLASES CASCADE CONSTRAINTS;
DROP TABLE CLASES_ENTRENADORES CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE CLASES CASCADE CONSTRAINTS;
DROP TABLE SUCURSALES CASCADE CONSTRAINTS;
DROP TABLE ENTRENADORES CASCADE CONSTRAINTS;
DROP TABLE MIEMBROS CASCADE CONSTRAINTS;
DROP TABLE MEMBRESIAS CASCADE CONSTRAINTS;

CREATE TABLE MEMBRESIAS (
    ID_MEM INT PRIMARY KEY,
    NOM_PLA VARCHAR(100),
    PRE_MEM NUMBER(10, 2),
    BEN_MEM VARCHAR(100)
);

CREATE TABLE MIEMBROS (
    ID_MIE INT PRIMARY KEY,
    RUT VARCHAR(12) NOT NULL,
    NOM_MIE VARCHAR(100),
    APE_MIE VARCHAR(100),
    FEC_NAC DATE,
    COR_ELE VARCHAR(100),
    TEL_MIE VARCHAR(15),
    FEC_INS DATE,
    ID_MEM INT, -- Clave foránea
    FOREIGN KEY (ID_MEM) REFERENCES MEMBRESIAS(ID_MEM)
);

CREATE TABLE ENTRENADORES (
    ID_ENT INT PRIMARY KEY,
    NOM_ENT VARCHAR(100),
    APE_ENT VARCHAR(100),
    ESP_ENT VARCHAR(100),
    CER_ENT VARCHAR(100)
);

CREATE TABLE SUCURSALES (
    ID_SUC INT PRIMARY KEY,
    DIR_SUC VARCHAR(100),
    CIU_SUC VARCHAR(100),
    TEL_SUC VARCHAR(15),
    HOR_APE DATE,
    HOR_CIE DATE
);

CREATE TABLE CLASES (
    ID_CLA INT PRIMARY KEY,
    NOM_CLA VARCHAR(100),
    NIV_DIF VARCHAR(100), -- principiante, intermedio, avanzado
    CAP_MAX INT,
    ID_SUC INT,
    FOREIGN KEY (ID_SUC) REFERENCES SUCURSALES(ID_SUC)
);

CREATE TABLE EQUIPOS (
    ID_EQU INT PRIMARY KEY,
    TIP_EQU VARCHAR(100),
    MAR_EQU VARCHAR(100)
);

CREATE TABLE RESERVAS (
    ID_RES INT PRIMARY KEY,
    ID_MIE INT,
    ID_EQU INT,
    ID_SUC INT,
    FEC_RES DATE,
    HOR_RES DATE,
    FOREIGN KEY (ID_MIE) REFERENCES MIEMBROS(ID_MIE),
    FOREIGN KEY (ID_EQU) REFERENCES EQUIPOS(ID_EQU),
    FOREIGN KEY (ID_SUC) REFERENCES SUCURSALES(ID_SUC),
    UNIQUE(ID_EQU, FEC_RES, HOR_RES)
);

CREATE TABLE CLASES_ENTRENADORES (
    ID_CLA INT,
    ID_ENT INT,
    FEC_CLA DATE,
    HOR_CLA DATE,
    PRIMARY KEY (ID_CLA, ID_ENT, FEC_CLA, HOR_CLA),
    FOREIGN KEY (ID_CLA) REFERENCES CLASES(ID_CLA),
    FOREIGN KEY (ID_ENT) REFERENCES ENTRENADORES(ID_ENT)
);

CREATE TABLE MIEMBROS_CLASES (
    ID_MIE INT,
    ID_CLA INT,
    FEC_INC DATE, 
    PRIMARY KEY (ID_MIE, ID_CLA),
    FOREIGN KEY (ID_MIE) REFERENCES MIEMBROS(ID_MIE),
    FOREIGN KEY (ID_CLA) REFERENCES CLASES(ID_CLA)
);

